---
all:
  children:
    vms:
      hosts:
        truenas:
          ansible_host: 10.0.10.201
        homeassistant:
          ansible_host: 10.0.10.211
        proxmox-backup:
          ansible_host: 10.0.10.250

    lxcs:
      children:
        docker_hosts:
          children:
            docker_media:
              hosts:
                docker-media:
                  ansible_host: 10.0.10.221
            docker_web:
              hosts:
                docker-web:
                  ansible_host: 10.0.10.222

        network_services:
          hosts:
            nginx:
              ansible_host: 10.0.10.231
            wireguard:
              ansible_host: 10.0.10.232
            pihole:
              ansible_host: 10.0.10.233

        gaming:
          hosts:
            pterodactyl:
              ansible_host: 10.0.10.241
