external_templates:
  - file: config/templates/collections.yml

collections:

  "Non-Collection":
    template:
      name: trakt-list
      list_author: furglitch
      list_name: misc-plex-sync
    minimum_items: 999