templates:
  trakt-list:
    minimum_items: 2
    libraries: Movies, TV Shows
    sync_to_users: all
    optional:
      - url_poster
      - ignore
    ignore_ids: <<ignore>>
    sonarr_add_missing: false
    radarr_add_missing: false
    trakt_list: "https://trakt.tv/<<list_path>>"
    url_poster: "<<poster>>"
    conditionals:
      list_path:
        default: "lists/official/<<list_name>>"
        conditions:
          - list_author.exists: true
            value: "users/<<list_author>>/lists/<<list_name>>"
      poster:
        conditions:
          - poster_id.exists: true
            value: "https://theposterdb.com/api/assets/<<poster_id>>"
