ip_local: "192.168.1.222"
ip_media: "{{ hostvars['docker-media']['ansible_host'] }}"
ip_nginx: "192.168.1.231"
ip_pterodactyl: "192.168.1.241"

ports:
  homarr: 8081
  vaultwarden: 8082
  nextcloud: 8083
  sillytavern: 8084
  proton_imap: 1143
  proton_smtp: 1025
  nginx_admin: 81
